name: Module

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-module-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-module-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-ccache-cache-
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses
      - name: Install ccache
        run: |
          sudo apt-get install -y ccache
          ccache -o max_size=2G
          ccache -o hash_dir=false
      - name: Build with Gradle
        run: |
          mkdir -p ~/.gradle/wrapper
          mkdir -p ~/.gradle/caches
          [ $(du -s ~/.gradle/wrapper | awk '{ print $1 }') -gt 250000 ] && rm -rf ~/.gradle/wrapper/* || true
          find ~/.gradle/caches -exec touch -d "2 days ago" {} + || true
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew assemble
      - name: Upload Shizuku API
        uses: actions/upload-artifact@v5
        with:
          name: api-release.aar
          path: './api/build/outputs/aar/api-release.aar'
      - name: Upload Provider
        uses: actions/upload-artifact@v5
        with:
          name: provider-release.aar
          path: './provider/build/outputs/aar/provider-release.aar'
      - name: Upload Demo
        uses: actions/upload-artifact@v5
        with:
          name: demo-release.apk
          path: './demo/build/outputs/apk/demo-release.apk'
      - name: Upload Rish
        uses: actions/upload-artifact@v5
        with:
          name: rish-release.aar
          path: './rish/build/outputs/aar/rish-release.aar'
      - name: Upload mappings
        uses: actions/upload-artifact@v5
        with:
          name: mappings
          path: |
            "module/build/outputs/mapping/release"
            "ui/build/outputs/mapping/release"
